### ISSUE TITLE
Query Params don't appear to get added to PSR-7 request, method is lowercased

### ISSUE THREAD

**Issue by jderr-mx** [agungsugiarto/codeigniter4-psr7bridge#1]
Hello, thank you for making this bridge available. I am using it to build a JSON:API in CI4 that requires PSR-7 requests and this has been helpful. 

I noticed a couple of issues
query params do not appear to get passed from the CI4 request to the PSR-7 request, it looks like you are using the URI segments only

https://github.com/agungsugiarto/codeigniter4-psr7bridge/blob/fdc8d71524dee36f5c54b2f49c6e20e72c0419a3/src/PsrHttpFactory.php#L72-L77

For some reason the CI4 request `getMethod()` returns the method in lowercase by default, passing  `true` returns it as upper case

https://github.com/agungsugiarto/codeigniter4-psr7bridge/blob/fdc8d71524dee36f5c54b2f49c6e20e72c0419a3/src/PsrHttpFactory.php#L55

**Comment by agungsugiarto** [comment]
Hello, thank you @jderr-mx for reporting the issue. It has already been fixed in PR #2.

**Comment by jderr-mx** [comment]
@agungsugiarto Awesome, thank you !
